name: Build and Push Docker Image

# Trigger this workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (to use multi-platform builds if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using Docker Hub password
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mb-admin:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mb-admin:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/mb-admin:latest

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mb-admin:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mb-admin:latest
